import { graphql } from "gatsby";
import * as React from "react";

// markup
const IndexPage = ({data}) => {
  return <>
    <p>I'm making this by following the Gatsby Tutorial.</p>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam fugiat dicta facilis in. Distinctio deleniti quos et dolor sapiente officiis quasi eum debitis magni, sit laborum molestiae nam dicta quas odit facilis voluptatibus? Eius deleniti impedit obcaecati delectus sint ipsam odio ullam ipsa reprehenderit eum, molestiae, laborum, non eaque? Debitis, quisquam fuga a est totam sit nesciunt dolor delectus consectetur rerum! Vitae, omnis reprehenderit quidem consectetur impedit velit esse cum sequi, alias eius odit quam voluptatem nihil eum maxime architecto excepturi unde nam sunt. Incidunt atque aut nihil ipsum voluptas iure illo ad qui, maiores eveniet recusandae minus quia magni cumque, perspiciatis voluptate natus vitae ex ab odit voluptatem, facilis provident. Repellat eum officiis porro obcaecati harum, saepe officia cumque architecto blanditiis facere, earum fugiat. Sunt culpa tempora harum aspernatur laborum ipsa, sequi, dolorem itaque temporibus facilis quos reiciendis, saepe molestiae dolorum dolores repellat. Tempore similique, tenetur est odit molestiae animi libero maxime eligendi possimus fugiat nobis, nam odio iusto quaerat eaque nemo. Voluptates, ut accusamus! Ducimus inventore quia quos porro nisi, molestias, ut quo esse nulla non ipsum vero minima facilis sequi quas? Quis similique autem alias asperiores dolore ab repellat laudantium! Soluta ullam eius fuga, enim a libero!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam fugiat dicta facilis in. Distinctio deleniti quos et dolor sapiente officiis quasi eum debitis magni, sit laborum molestiae nam dicta quas odit facilis voluptatibus? Eius deleniti impedit obcaecati delectus sint ipsam odio ullam ipsa reprehenderit eum, molestiae, laborum, non eaque? Debitis, quisquam fuga a est totam sit nesciunt dolor delectus consectetur rerum! Vitae, omnis reprehenderit quidem consectetur impedit velit esse cum sequi, alias eius odit quam voluptatem nihil eum maxime architecto excepturi unde nam sunt. Incidunt atque aut nihil ipsum voluptas iure illo ad qui, maiores eveniet recusandae minus quia magni cumque, perspiciatis voluptate natus vitae ex ab odit voluptatem, facilis provident. Repellat eum officiis porro obcaecati harum, saepe officia cumque architecto blanditiis facere, earum fugiat. Sunt culpa tempora harum aspernatur laborum ipsa, sequi, dolorem itaque temporibus facilis quos reiciendis, saepe molestiae dolorum dolores repellat. Tempore similique, tenetur est odit molestiae animi libero maxime eligendi possimus fugiat nobis, nam odio iusto quaerat eaque nemo. Voluptates, ut accusamus! Ducimus inventore quia quos porro nisi, molestias, ut quo esse nulla non ipsum vero minima facilis sequi quas? Quis similique autem alias asperiores dolore ab repellat laudantium! Soluta ullam eius fuga, enim a libero!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam fugiat dicta facilis in. Distinctio deleniti quos et dolor sapiente officiis quasi eum debitis magni, sit laborum molestiae nam dicta quas odit facilis voluptatibus? Eius deleniti impedit obcaecati delectus sint ipsam odio ullam ipsa reprehenderit eum, molestiae, laborum, non eaque? Debitis, quisquam fuga a est totam sit nesciunt dolor delectus consectetur rerum! Vitae, omnis reprehenderit quidem consectetur impedit velit esse cum sequi, alias eius odit quam voluptatem nihil eum maxime architecto excepturi unde nam sunt. Incidunt atque aut nihil ipsum voluptas iure illo ad qui, maiores eveniet recusandae minus quia magni cumque, perspiciatis voluptate natus vitae ex ab odit voluptatem, facilis provident. Repellat eum officiis porro obcaecati harum, saepe officia cumque architecto blanditiis facere, earum fugiat. Sunt culpa tempora harum aspernatur laborum ipsa, sequi, dolorem itaque temporibus facilis quos reiciendis, saepe molestiae dolorum dolores repellat. Tempore similique, tenetur est odit molestiae animi libero maxime eligendi possimus fugiat nobis, nam odio iusto quaerat eaque nemo. Voluptates, ut accusamus! Ducimus inventore quia quos porro nisi, molestias, ut quo esse nulla non ipsum vero minima facilis sequi quas? Quis similique autem alias asperiores dolore ab repellat laudantium! Soluta ullam eius fuga, enim a libero!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam fugiat dicta facilis in. Distinctio deleniti quos et dolor sapiente officiis quasi eum debitis magni, sit laborum molestiae nam dicta quas odit facilis voluptatibus? Eius deleniti impedit obcaecati delectus sint ipsam odio ullam ipsa reprehenderit eum, molestiae, laborum, non eaque? Debitis, quisquam fuga a est totam sit nesciunt dolor delectus consectetur rerum! Vitae, omnis reprehenderit quidem consectetur impedit velit esse cum sequi, alias eius odit quam voluptatem nihil eum maxime architecto excepturi unde nam sunt. Incidunt atque aut nihil ipsum voluptas iure illo ad qui, maiores eveniet recusandae minus quia magni cumque, perspiciatis voluptate natus vitae ex ab odit voluptatem, facilis provident. Repellat eum officiis porro obcaecati harum, saepe officia cumque architecto blanditiis facere, earum fugiat. Sunt culpa tempora harum aspernatur laborum ipsa, sequi, dolorem itaque temporibus facilis quos reiciendis, saepe molestiae dolorum dolores repellat. Tempore similique, tenetur est odit molestiae animi libero maxime eligendi possimus fugiat nobis, nam odio iusto quaerat eaque nemo. Voluptates, ut accusamus! Ducimus inventore quia quos porro nisi, molestias, ut quo esse nulla non ipsum vero minima facilis sequi quas? Quis similique autem alias asperiores dolore ab repellat laudantium! Soluta ullam eius fuga, enim a libero!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam fugiat dicta facilis in. Distinctio deleniti quos et dolor sapiente officiis quasi eum debitis magni, sit laborum molestiae nam dicta quas odit facilis voluptatibus? Eius deleniti impedit obcaecati delectus sint ipsam odio ullam ipsa reprehenderit eum, molestiae, laborum, non eaque? Debitis, quisquam fuga a est totam sit nesciunt dolor delectus consectetur rerum! Vitae, omnis reprehenderit quidem consectetur impedit velit esse cum sequi, alias eius odit quam voluptatem nihil eum maxime architecto excepturi unde nam sunt. Incidunt atque aut nihil ipsum voluptas iure illo ad qui, maiores eveniet recusandae minus quia magni cumque, perspiciatis voluptate natus vitae ex ab odit voluptatem, facilis provident. Repellat eum officiis porro obcaecati harum, saepe officia cumque architecto blanditiis facere, earum fugiat. Sunt culpa tempora harum aspernatur laborum ipsa, sequi, dolorem itaque temporibus facilis quos reiciendis, saepe molestiae dolorum dolores repellat. Tempore similique, tenetur est odit molestiae animi libero maxime eligendi possimus fugiat nobis, nam odio iusto quaerat eaque nemo. Voluptates, ut accusamus! Ducimus inventore quia quos porro nisi, molestias, ut quo esse nulla non ipsum vero minima facilis sequi quas? Quis similique autem alias asperiores dolore ab repellat laudantium! Soluta ullam eius fuga, enim a libero!
    </p>
  </>;
};

// export const query = graphql`
  
// `

export default IndexPage;
